#!/bin/bash
#SBATCH --account=share-ie-itk
#SBATCH --partition=CPUQ
#SBATCH --time=5:00:00
#SBATCH --nodes=1             # 1 compute nodes
#SBATCH --cpus-per-task=32     # 2 CPU cores
#SBATCH --mem=128G             # GB memory
#SBATCH --output=output.txt    # Log file
#SBATCH --mail-user=trulsc00@gmail.com
#SBATCH --mail-type=ALL

# Go to submission folder
cd ~/Label-ais-ers/Master-prework/label_ais_pts_w_ers

# Load Python
module purge
module load Python/3.11.5-GCCcore-13.2.0

# Activate venv
source ~/venv/myenv/bin/activate

# Run your script
python label_pts.py